version: '3'

services:
  app:
    build: .
    volumes: [".:/opt/app"]
    ports:
      - 7100:7100
    depends_on: 
      - db
  db:
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports: 
      - 0.0.0.0:7203:3306